


const main = async () => {
  try {
    console.log("main");
    return;
  } catch (err) {
    console.log(err.message);
  }
};

main();
